### ISSUE TITLE
Idea: Use plugins for theme distribution

### ISSUE THREAD

**Issue by zpao** [zpao/hypertheme#1]
Seems like it could be a better way to do this instead of having to download files some other way.

**Comment by Anahkiasen** [comment]
👍  for this, current way to manage themes is a little cumbersome

**Comment by zpao** [comment]
I think this just became more reasonable - 0.5 just exposed some sort of access to installed plugins. It also exposed its own theming which is a great start but I foresee some issues.

**Comment by zpao** [comment]
Themes are properly supported by Hyper now (for years really) so this project is no longer necessary. Cleaning up.
