### ISSUE TITLE
`config.theme` is not supported

### ISSUE THREAD

**Issue by montogeek** [zpao/hypertheme#3]
`config.theme` option is not officially supported by HyperTerm, what about handle them using plugins that exports the colors palette?

Some examples: https://github.com/mdo/hyperterm-atom-dark and https://github.com/jxnblk/hyperterminator/blob/master/index.js

**Comment by zpao** [comment]
Hyperterminator uses the new `decorateConfig` API. atom-dark uses the same pattern I have here (middleware which basically does what the `decorateConfig` API does. I'd love to make it so themes just export an object that a theme plugin like myself or hyperterm natively can consume. Let's followup in #1 as needed though.
