### ISSUE TITLE
Quick switch between themes

### ISSUE THREAD

**Issue by jimthedev** [zpao/hypertheme#4]
One nice feature in iterm is the ability to type a command to switch between themes. Would be nice to see this in hypertheme. Specifically, if you're going to be presenting on a bad projector, you might want to quickly switch to a high contrast theme.

**Comment by zpao** [comment]
You get live reloading on config file changes already so that's pretty quick (but does involved `$EDITOR` right now so perhaps awkward. I was thinking it would be cool to hook into the menu UI and expose something there for fast switching.

**Comment by zpao** [comment]
Themes are properly supported by Hyper now (for years really) so this project is no longer necessary. Cleaning up.
