### ISSUE TITLE
Config example

### ISSUE THREAD

**Issue by tyler-reitz** [zpao/hypertheme#6]
Followed the instructions but still having trouble getting it configured properly:

1. created a `~/.hyperterm_themes` 

2. Downloaded a theme: `~/.hyperterm_themes/hyperterm-retro.js`

3. And added a `theme` field to my config:

    ```
   …
   theme: 'hyperterm-retro',
   …
    ``` 

If I could get an example to follow, that'd be great!

Thanks

**Comment by ishanSrt** [comment]
you have to add `config.theme` field not `theme` @tyler-reitz

**Comment by ishanSrt** [comment]
an example would still be great

**Comment by zpao** [comment]
Themes are properly supported by Hyper now (for years really) so this project is no longer necessary. Cleaning up.
